// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"chopipay/config/db/pg"
	"chopipay/config/server"
	"chopipay/internal/http/controllers"
	"chopipay/internal/http/controllers/business"
	"chopipay/internal/http/services"
	pg2 "chopipay/internal/repository/pg"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	v := server.LoadEnvironment()
	db := pg.InitConnection(v)
	salesRepository := pg2.NewSalesRepository(db)
	productRepository := pg2.NewProductRepository(db)
	shopRepository := pg2.NewShopRepository(db)
	personalRepository := pg2.NewPersonalRepository(db)
	personalCredentialsRepository := pg2.NewPersonalCredentialsRepository(db)
	mpMerchantOrderPaymentsRepository := pg2.NewMpMerchantOrderPaymentsRepository(db)
	mpMerchantOrderRepository := pg2.NewMpMerchantOrderRepository(db)
	mpPayerRepository := pg2.NewMpPayerRepository(db)
	mpPaymentRepository := pg2.NewMpPaymentRepository(db)
	paymentMethodRepository := pg2.NewPaymentMethodRepository(db)
	saleProductsRepository := pg2.NewSaleProductsRepository(db)
	salesStatusRepository := pg2.NewSalesStatusRepository(db)
	salesService := services.NewSalesService(salesRepository, personalRepository)
	productService := services.NewProductService(productRepository)
	shopService := services.NewShopService(shopRepository)
	personalService := services.NewPersonalService(personalRepository)
	personalCredentialsService := services.NewPersonalCredentialsService(personalRepository, personalCredentialsRepository)
	salesController := business.NewSalesController(salesService)
	productController := controllers.NewProductController(productService, personalService)
	shopController := controllers.NewShopController(shopService, productService)
	personalController := controllers.NewPersonalController(personalService, shopService, personalCredentialsService)
	initialization := NewDiInit(salesRepository, productRepository, shopRepository, personalRepository, personalCredentialsRepository, mpMerchantOrderPaymentsRepository, mpMerchantOrderRepository, mpPayerRepository, mpPaymentRepository, paymentMethodRepository, saleProductsRepository, salesStatusRepository, salesService, productService, shopService, personalService, personalCredentialsService, salesController, productController, shopController, personalController)
	return initialization
}

// injector.go:

var envVars = wire.NewSet(server.LoadEnvironment)

var pgDb = wire.NewSet(pg.InitConnection)

/*	Repositories */
var salesRepoSet = wire.NewSet(pg2.NewSalesRepository)

var productRepoSet = wire.NewSet(pg2.NewProductRepository)

var shopRepoSet = wire.NewSet(pg2.NewShopRepository)

var personalRepoSet = wire.NewSet(pg2.NewPersonalRepository)

var personalCredentialsRepoSet = wire.NewSet(pg2.NewPersonalCredentialsRepository)

var mpMerchantOrderPaymentsRepoSet = wire.NewSet(pg2.NewMpMerchantOrderPaymentsRepository)

var mpMerchantOrderRepoSet = wire.NewSet(pg2.NewMpMerchantOrderRepository)

var mpPayerRepoSet = wire.NewSet(pg2.NewMpPayerRepository)

var mpPaymentRepoSet = wire.NewSet(pg2.NewMpPaymentRepository)

var paymentMethodRepoSet = wire.NewSet(pg2.NewPaymentMethodRepository)

var saleProductsRepoSet = wire.NewSet(pg2.NewSaleProductsRepository)

var saleStatusRepoSet = wire.NewSet(pg2.NewSalesStatusRepository)

/*	Services */
var salesServiceSet = wire.NewSet(services.NewSalesService)

var productServiceSet = wire.NewSet(services.NewProductService)

var shopServiceSet = wire.NewSet(services.NewShopService)

var personalServiceSet = wire.NewSet(services.NewPersonalService)

var personalCredentialsServiceSet = wire.NewSet(services.NewPersonalCredentialsService)

/*	Controllers */
var salesCtrlSet = wire.NewSet(business.NewSalesController)

var productCtrlSet = wire.NewSet(controllers.NewProductController)

var shopCtrlSet = wire.NewSet(controllers.NewShopController)

var personalCtrlSet = wire.NewSet(controllers.NewPersonalController)
